# Generated by Django 5.2.5 on 2025-08-24 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Tema')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('suggested_topics', models.JSONField(blank=True, help_text='Tópicos sugeridos pelo primeiro agente da OpenAI', null=True, verbose_name='Tópicos Sugeridos')),
                ('topics_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Tópicos gerados em')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('simple', 'Post Simples'), ('article', 'Artigo')], max_length=10, verbose_name='Tipo de Post')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('topic', models.CharField(help_text='Tópico específico usado para gerar este post', max_length=200, verbose_name='Tópico')),
                ('seo_title', models.CharField(help_text='Título otimizado para SEO (máx. 60 caracteres)', max_length=60, verbose_name='Título SEO')),
                ('seo_description', models.CharField(help_text='Descrição otimizada para SEO (máx. 160 caracteres)', max_length=160, verbose_name='Descrição SEO')),
                ('link', models.URLField(blank=True, help_text='Link relacionado ao post (opcional)', null=True, verbose_name='Link')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Postagem')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Agendada')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado'), ('published', 'Publicado'), ('scheduled', 'Agendado')], default='draft', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('generated_at', models.DateTimeField(blank=True, help_text='Data e hora em que o conteúdo foi gerado pela IA', null=True, verbose_name='Gerado em')),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt usado para gerar o conteúdo', verbose_name='Prompt de Geração')),
                ('ai_model_used', models.CharField(blank=True, max_length=50, verbose_name='Modelo de IA Usado')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.theme', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'unique_together': {('theme', 'post_type')},
            },
        ),
    ]
