# Generated by Django 5.2.5 on 2025-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_theme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promotional_post',
            field=models.TextField(blank=True, help_text='Post resumido para promover artigos no LinkedIn', verbose_name='Post Promocional'),
        ),
    ]
