# Generated by Django 5.2.5 on 2025-08-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_promotional_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
