# Generated by Django 5.2.5 on 2025-08-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Aguardando'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='idle', max_length=20, verbose_name='Status de Processamento'),
        ),
        migrations.AddField(
            model_name='theme',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Aguardando'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='idle', max_length=20, verbose_name='Status de Processamento'),
        ),
    ]
