# Generated by Django 5.2.5 on 2025-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_processing_status_theme_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_prompt',
            field=models.TextField(blank=True, help_text='Descrição detalhada para geração de imagem de capa do artigo', verbose_name='Prompt da Imagem de Capa'),
        ),
    ]
