# Generated by Django 5.2.5 on 2025-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_cover_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_processing',
            field=models.BooleanField(default=False, verbose_name='Está Processando'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_processing',
            field=models.BooleanField(default=False, verbose_name='Está Processando'),
        ),
    ]
