# Generated by Django 5.2.5 on 2025-09-05 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_is_processing_theme_is_processing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterField(
            model_name='post',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='AI Model Used'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image_prompt',
            field=models.TextField(blank=True, help_text='Detailed description for article cover image generation', verbose_name='Cover Image Prompt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when content was generated by AI', null=True, verbose_name='Generated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='generation_prompt',
            field=models.TextField(blank=True, help_text='Prompt used to generate content', verbose_name='Generation Prompt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_processing',
            field=models.BooleanField(default=False, verbose_name='Is Processing'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, help_text='Post related link (optional)', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('simple', 'Simple Post'), ('article', 'Article')], max_length=10, verbose_name='Post Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='promotional_post',
            field=models.TextField(blank=True, help_text='Summarized post to promote articles on LinkedIn', verbose_name='Promotional Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(help_text='SEO optimized description (max. 160 characters)', max_length=160, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(help_text='SEO optimized title (max. 60 characters)', max_length=60, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.theme', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(help_text='Specific topic used to generate this post', max_length=200, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_processing',
            field=models.BooleanField(default=False, verbose_name='Is Processing'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='suggested_topics',
            field=models.JSONField(blank=True, help_text='Topics suggested by the first OpenAI agent', null=True, verbose_name='Suggested Topics'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Theme Title'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='topics_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Topics generated at'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
