# Generated by Django 5.2.5 on 2025-09-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_theme_options_alter_post_ai_model_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_provider_used',
            field=models.CharField(blank=True, help_text='AI provider used to generate content (openai, grok, gemini)', max_length=20, verbose_name='AI Provider Used'),
        ),
    ]
